document.write('<div class="header">') 
document.write('<ul class="topnav">')
document.write('<li><a href="../index.html">Inicio</a></li>')
document.write('<li><a href="../titulares.html">Nuestros Titulares</a>') 
document.write('<li><a href="../titulares_1.html">Origenes Devocion</a></li>')
document.write('<li><a href="../junta.html">Junta Gobierno</a></li>')                               
document.write('<li><a href="../secretaria.html">Secretaria</a></li>')
//document.write('<li><a href="../bcaridad.html">Bolsa Caridad</a></li>')  
document.write('<li><a href="../parroquia.html">Parroquia</a></li>')
document.write('<li><a href="../enlaces.html">Enlaces de Interes</a></li>')            
document.write('<li><a href="./multimedia.html">Galeria</a>')
document.write('</li>')
document.write('</ul>')
document.write('</div>')	