
document.write('	<script type="text/javascript">') 
document.write('	    $(document).ready(function(){')  
document.write('	       $("ul.subnav").parent().append("<span></span>");')  
document.write('	       $("ul.topnav li span").click(function() {')  
document.write('            $(this).parent().find("ul.subnav").slideDown('fast').show();')  
document.write('            $(this).parent().hover(function() {')  
document.write('            }, function(){')  
document.write('                $(this).parent().find("ul.subnav").slideUp('slow'); //When the mouse hovers out of the subnav, move it back up')  
document.write('            });')  
document.write('            }).hover(function() {')  
document.write('                $(this).addClass("subhover");')  
document.write('            }, function(){')  
document.write('                $(this).removeClass("subhover"); //On hover out, remove class "subhover"')  
document.write('        });')  
document.write('    });')  
document.write('	</script>')